# Generated by Django 3.2.9 on 2022-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('castel', models.IntegerField()),
                ('senq', models.IntegerField()),
                ('doppel', models.IntegerField()),
                ('george', models.IntegerField()),
                ('total_payment', models.FloatField()),
            ],
        ),
    ]
