# Generated by Django 2.2.18 on 2022-04-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('castel', models.IntegerField()),
                ('senq', models.IntegerField()),
                ('doppel', models.IntegerField()),
                ('george', models.IntegerField()),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('castel', models.IntegerField()),
                ('senq', models.IntegerField()),
                ('doppel', models.IntegerField()),
                ('george', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.Profile')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('profile', models.OneToOneField(on_delete=None, to='Company.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Agent')),
                ('profile', models.OneToOneField(on_delete=None, to='Company.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('castel', models.IntegerField()),
                ('senq', models.IntegerField()),
                ('doppel', models.IntegerField()),
                ('george', models.IntegerField()),
                ('total_payment', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=None, to='Company.Agent')),
                ('store', models.ForeignKey(on_delete=None, to='Company.Agent_store')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Agent')),
                ('profile', models.OneToOneField(on_delete=None, to='Company.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_store_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.Profile')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.Agent_store')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('castel', models.IntegerField()),
                ('senq', models.IntegerField()),
                ('doppel', models.IntegerField()),
                ('george', models.IntegerField()),
                ('total_payment', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=None, to='Company.Agent')),
                ('store', models.ForeignKey(on_delete=None, to='Company.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Agent')),
                ('profile', models.OneToOneField(on_delete=None, to='Company.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='profile',
            field=models.OneToOneField(on_delete=None, to='Company.Profile'),
        ),
        migrations.AddField(
            model_name='agent',
            name='region',
            field=models.ForeignKey(on_delete=None, to='Company.Region'),
        ),
    ]
